In [1]:
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

# Array 연산

In [ ]:
#1. 기본 연산 (합, 차, 곱, 나눗셈 등)
# 동일한 위치에 있는 요소들끼리의 연산

In [4]:
# 동일한 크기의 array 2개
n1 = np.array([[1,2,3], [4,3,6]])
n2 = np.array([[7,10,2], [2,6,9]])

In [5]:
n1+n2

array([[ 8, 12,  5],
       [ 6,  9, 15]])

In [6]:
n1-n2

array([[-6, -8,  1],
       [ 2, -3, -3]])

In [7]:
n1*n2

array([[ 7, 20,  6],
       [ 8, 18, 54]])

In [8]:
n1 * 10

array([[10, 20, 30],
       [40, 30, 60]])

In [9]:
n1 > 5

array([[False, False, False],
       [False, False,  True]])

In [10]:
n1[n1>5]

array([6])

In [ ]:
#2. 배열의 Broadcasting
#서로 크기가 다른 array들의 연산이 가능하도록 배열을 자동적으로 변환하여 연산 수행

In [11]:
n1

array([[1, 2, 3],
       [4, 3, 6]])

In [12]:
n3 = np.array([1,8,10])

In [13]:
n1+n3

array([[ 2, 10, 13],
       [ 5, 11, 16]])

In [17]:
n4 = np.array([1,2,3]).reshape(3,1)
n4

array([[1],
       [2],
       [3]])

In [18]:
n3+n4

array([[ 2,  9, 11],
       [ 3, 10, 12],
       [ 4, 11, 13]])

In [ ]:
#3. 통계를 위한 연산
# - 배열의 합, 평균, 표준편차, 분산, 최소값, 최대값, 누적합, 누적곱 등

In [20]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr1.sum()

45

In [23]:
n2

array([[ 7, 10,  2],
       [ 2,  6,  9]])

In [24]:
n2.sum()

36

In [25]:
# axis를 부여
n2.sum(axis=0)

array([ 9, 16, 11])

In [26]:
n2.sum(axis=1)

array([19, 17])

In [27]:
n2.mean()

6.0

In [28]:
n2.mean(axis=0)

array([4.5, 8. , 5.5])

In [29]:
n2.mean(axis=1)

array([6.33333333, 5.66666667])

In [30]:
n2.min()

2

In [31]:
n2.min(axis=0)

array([2, 6, 2])

In [32]:
n2.min(axis=1)

array([2, 2])

In [34]:
n2.max()

10

In [35]:
n2.std()

3.1091263510296048

In [36]:
n2.cumprod()

array([    7,    70,   140,   280,  1680, 15120])

In [38]:
n2.cumsum()

array([ 7, 17, 19, 21, 27, 36])

In [ ]:
# 행렬 연산

In [39]:
A = np.array([1,2,3,4]).reshape(2,2)
B = np.array([3,1,9,10]).reshape(2,2)

In [40]:
A.dot(B)

array([[21, 21],
       [45, 43]])

In [41]:
np.dot(A,B)

array([[21, 21],
       [45, 43]])

In [42]:
B.dot(A)

array([[ 6, 10],
       [39, 58]])

In [43]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [44]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [45]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [47]:
A.dot(np.linalg.inv(A))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])