# NumPy
- C언어로 구현된 파이썬 라이브러리
- array 단위로 데이터를 관리하며 이에 대해 연산을 수행
- array는 Dynamic type을 지원하지 않음 (한 타입만 지원)


In [42]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
# 넘파이 버전 확인 
np.__version__

'1.21.5'

In [4]:
# 파이썬 버전 확인
import sys
sys.version

'3.9.13 (main, Aug 25 2022, 18:29:29) \n[Clang 12.0.0 ]'

### 1. Array 정의 및 사용
- 시퀀스 데이터(리스트, 튜플 등)로부터 배열 생성

In [6]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [8]:
arr1 = np.array(data1)

In [9]:
type(arr1)

numpy.ndarray

In [11]:
data2 = [1,2,3,4,5]
data2

[1, 2, 3, 4, 5]

In [12]:
arr2 = np.array(data2)

In [13]:
arr2

array([1, 2, 3, 4, 5])

In [14]:
print(arr2)

[1 2 3 4 5]


In [20]:
data = arr2.tolist()

In [21]:
data

[1, 2, 3, 4, 5]

In [ ]:
#array 크기 확인 : shape

In [23]:
arr1

array([1, 2, 3])

In [22]:
arr1.shape

(3,)

In [24]:
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [25]:
arr2.shape

(5,)

In [ ]:
#array 자료형 확인 : dtype

In [26]:
arr1.dtype

dtype('int64')

In [27]:
arr2.dtype

dtype('int64')

In [29]:
arr3 = np.array(arr2)
arr3

array([1, 2, 3, 4, 5])

In [30]:
# 2차원 array 생성
arr4 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
arr4.shape

(4, 3)

In [32]:
arr4.dtype

dtype('int64')

In [34]:
# 또다른 2차원 array (정수와 실수가 섞여 있을 때)
arr5 = np.array([[1,2,3.5], [4,5,7]])
arr5

array([[1. , 2. , 3.5],
       [4. , 5. , 7. ]])

In [35]:
arr5.dtype

dtype('float64')

In [43]:
arr5.shape

(2, 3)

In [ ]:
# 범위를 지정해 배열 생성
# np.arange() 함수
# np.linspace() 함수

In [44]:
#1. np.arange()
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [47]:
#reshape 메서드 사용
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
#2. np.linspace() 함수
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [49]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [50]:
# 특별한 형태의 배열 생성
# np.zeros, np.ones, np.eye

In [54]:
# np.zeros : 모두 0으로 채움
np.zeros(10) #1차원
np.zeros((2,3)) #2차원

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.zeros(15).reshape(3,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
# np.ones : 모두 1로 채움
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
np.ones(10).reshape(2,5)
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
np.ones((2,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
np.ones((2,5), dtype='float32')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [62]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [63]:
# np.eye : 대각 요소가 0인 배열
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [64]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.eye(3, k=1, dtype=int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [67]:
# 대각 요소가 1인 배열 생성2 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 초기화되지 않은 배열 생성 : np.empty

In [68]:
np.empty(10)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

In [69]:
np.empty(10).reshape(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [72]:
np.empty((3,4))

array([[0.00000000e+000, 2.42092166e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.04082753e-047, 6.25789480e-091,
        3.85589020e-057],
       [5.50924801e+169, 1.25844120e-047, 6.99196247e+228,
        2.60097353e-306]])

In [74]:
# 요소를 같은 값으로 채운 배열 생성 : np.full
np.full((3,3),3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [75]:
np.full(3,3)

array([3, 3, 3])

In [76]:
# 난수 배열 생성
#random.rand(), random.randint()
np.random.rand()

0.07164477168238093

In [78]:
np.random.rand(2,3)

array([[0.13788366, 0.80646502, 0.79238775],
       [0.17447836, 0.6524555 , 0.42789177]])

In [79]:
np.random.rand(2,2,3)

array([[[0.3540494 , 0.90331159, 0.42041119],
        [0.414311  , 0.79296871, 0.13436612]],

       [[0.48262685, 0.12701513, 0.87215868],
        [0.29521026, 0.38793552, 0.07837681]]])

In [83]:
np.random.randint(1,10)

5

In [84]:
np.random.randint(10)

5

In [86]:
np.random.randint(10, size = 4)

array([0, 5, 9, 5])

In [87]:
np.random.randint(2,10, size = (3,2))

array([[8, 5],
       [3, 4],
       [5, 2]])

In [93]:
np.random.randint(1, size = (3,4))
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])