In [1]:
import pandas as pd
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity='all'

# 데이터 변환 
- 단위 환산
- 자료형 변환

In [3]:
auto=pd.read_csv('데이터분석&시각화/workspace/pandas/data/auto_mpg.csv', header=None)
auto

auto.info()

0  1      2      3       4     5   6  7                          8
0    18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1    15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2    18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3    16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4    17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino
..    ... ..    ...    ...     ...   ...  .. ..                        ...
393  27.0  4  140.0  86.00  2790.0  15.6  82  1            ford mustang gl
394  44.0  4   97.0  52.00  2130.0  24.6  82  2                  vw pickup
395  32.0  4  135.0  84.00  2295.0  11.6  82  1              dodge rampage
396  28.0  4  120.0  79.00  2625.0  18.6  82  1                ford ranger
397  31.0  4  119.0  82.00  2720.0  19.4  82  1                 chevy s-10

[398 rows x 9 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       398 non-null    float64
 1   1       398 non-null    int64  
 2   2       398 non-null    float64
 3   3       398 non-null    object 
 4   4       398 non-null    float64
 5   5       398 non-null    float64
 6   6       398 non-null    int64  
 7   7       398 non-null    int64  
 8   8       398 non-null    object 
dtypes: float64(4), int64(3), object(2)
memory usage: 28.1+ KB


Attribute Information:

1. mpg: continuous
2. cylinders: multi-valued discrete
3. displacement: continuous
4. horsepower: continuous
5. weight: continuous
6. acceleration: continuous
7. model year: multi-valued discrete
8. origin: multi-valued discrete
9. car name: string (unique for each instance)

In [4]:
#칼럼 지정
auto.columns=['mpg', 'cylinders', 'displacement',
             'horsepower', 'weight', 'acceleration', 
             'model_year', 'origin', 'car_name']
auto.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model_year  \
0  18.0          8         307.0      130.0  3504.0          12.0          70   
1  15.0          8         350.0      165.0  3693.0          11.5          70   
2  18.0          8         318.0      150.0  3436.0          11.0          70   
3  16.0          8         304.0      150.0  3433.0          12.0          70   
4  17.0          8         302.0      140.0  3449.0          10.5          70   

   origin                   car_name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

### 1. 단위 환산
- mpg컬럼의 단위 환산 (mile per gallon)
- 1 mile = 1.60934km 
- 1 gallon = 3.75841L

In [5]:
auto['km/L']=round(auto.mpg*1.60934/3.75841, 2)
auto['km/L'].head()

0    7.71
1    6.42
2    7.71
3    6.85
4    7.28
Name: km/L, dtype: float64

### 2. 자료형 변환 

In [6]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car_name      398 non-null    object 
 9   km/L          398 non-null    float64
dtypes: float64(5), int64(3), object(2)
memory usage: 31.2+ KB


In [7]:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
km/L            float64
dtype: object

In [8]:
#horsepower - 수치형이지만, 문자열로 저장되어 있음
#데이터 타입 변경 필요 ! 

In [9]:
auto.horsepower.unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [10]:
auto.horsepower.isnull().sum()

0

In [11]:
auto.horsepower.value_counts()

150.0    22
90.00    20
88.00    19
110.0    18
100.0    17
         ..
61.00     1
93.00     1
148.0     1
152.0     1
82.00     1
Name: horsepower, Length: 94, dtype: int64

In [12]:
auto.horsepower.replace('?', np.nan, inplace = True)
auto.horsepower.isnull().sum()

6

In [13]:
auto.dropna(subset=['horsepower'], inplace=True)
auto.horsepower.unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [14]:
auto.horsepower=auto.horsepower.astype('float')
auto.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        392 non-null    float64
 5   acceleration  392 non-null    float64
 6   model_year    392 non-null    int64  
 7   origin        392 non-null    int64  
 8   car_name      392 non-null    object 
 9   km/L          392 non-null    float64
dtypes: float64(6), int64(3), object(1)
memory usage: 33.7+ KB


In [15]:
# origin 컬럼 - 국가 이름을 코드화 
# 1, 2, 3 = USA, EU, JPN

In [16]:
auto.origin.unique()
auto.origin.replace({1:'USA', 2:'EU',3:'JPN'}, inplace=True)
auto.origin=auto.origin.astype('category')

array([1, 3, 2])

In [17]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 392 entries, 0 to 397
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   mpg           392 non-null    float64 
 1   cylinders     392 non-null    int64   
 2   displacement  392 non-null    float64 
 3   horsepower    392 non-null    float64 
 4   weight        392 non-null    float64 
 5   acceleration  392 non-null    float64 
 6   model_year    392 non-null    int64   
 7   origin        392 non-null    category
 8   car_name      392 non-null    object  
 9   km/L          392 non-null    float64 
dtypes: category(1), float64(6), int64(2), object(1)
memory usage: 31.1+ KB


In [18]:
#model year 컬럼
auto.head()
auto.model_year.unique()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0  3504.0          12.0   
1  15.0          8         350.0       165.0  3693.0          11.5   
2  18.0          8         318.0       150.0  3436.0          11.0   
3  16.0          8         304.0       150.0  3433.0          12.0   
4  17.0          8         302.0       140.0  3449.0          10.5   

   model_year origin                   car_name  km/L  
0          70    USA  chevrolet chevelle malibu  7.71  
1          70    USA          buick skylark 320  6.42  
2          70    USA         plymouth satellite  7.71  
3          70    USA              amc rebel sst  6.85  
4          70    USA                ford torino  7.28

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [19]:
auto.model_year=auto.model_year.astype('category')
auto.model_year.unique()

[70, 71, 72, 73, 74, ..., 78, 79, 80, 81, 82]
Length: 13
Categories (13, int64): [70, 71, 72, 73, ..., 79, 80, 81, 82]

### 범주형 데이터 처리 

###### 1. 구간분할(bining) 

In [20]:
#horsepower : 저출력/보통출력/고출력 3구간으로 구간화(binning)

In [22]:
hist, bins = np.histogram(auto.horsepower, bins=3)
bins

array([ 46.        , 107.33333333, 168.66666667, 230.        ])

In [24]:
labels = ['저출력', '보통출력', '고출력']
auto['hp_bin'] = pd.cut(auto.horsepower, bins=bins, 
                       labels=labels,
                       include_lowest=True)
auto[['horsepower', 'hp_bin']]

horsepower hp_bin
0         130.0   보통출력
1         165.0   보통출력
2         150.0   보통출력
3         150.0   보통출력
4         140.0   보통출력
..          ...    ...
393        86.0    저출력
394        52.0    저출력
395        84.0    저출력
396        79.0    저출력
397        82.0    저출력

[392 rows x 2 columns]

In [25]:
pd.get_dummies(auto.hp_bin)

저출력  보통출력  고출력
0      0     1    0
1      0     1    0
2      0     1    0
3      0     1    0
4      0     1    0
..   ...   ...  ...
393    1     0    0
394    1     0    0
395    1     0    0
396    1     0    0
397    1     0    0

[392 rows x 3 columns]

###  정규화
- 숫자 데이터의 상대적인 크기 차이를 제거하기 위해, 데이터 값을 동일한 크기 기준으로 나눈 비율로 나타낸 변환
- 특성 벡터의 길이는 상관 없고 데이터의 방향만이 중요할 때 주로 사용

In [26]:
# 데이터를 |최대값|으로 나눔 

In [27]:
auto.horsepower.dtypes

dtype('float64')

In [28]:
auto.horsepower.describe()

count    392.000000
mean     104.469388
std       38.491160
min       46.000000
25%       75.000000
50%       93.500000
75%      126.000000
max      230.000000
Name: horsepower, dtype: float64

In [31]:
hp1 = auto.horsepower / abs(auto.horsepower.max())
hp1.describe()

count    392.000000
mean       0.454215
std        0.167353
min        0.200000
25%        0.326087
50%        0.406522
75%        0.547826
max        1.000000
Name: horsepower, dtype: float64

In [35]:
# min-max scailing : 최소값은 0, 최대값은 1이 되도록 변환 
# 분모 : 최대 - 최소
# 분자 : 각 데이터 값 - 최소 

min_max = auto.horsepower.max()-auto.horsepower.min()
min_x = auto.horsepower - auto.horsepower.min()
hp2 = min_x/min_max
hp2
hp2.describe()

0      0.456522
1      0.646739
2      0.565217
3      0.565217
4      0.510870
         ...   
393    0.217391
394    0.032609
395    0.206522
396    0.179348
397    0.195652
Name: horsepower, Length: 392, dtype: float64

count    392.000000
mean       0.317768
std        0.209191
min        0.000000
25%        0.157609
50%        0.258152
75%        0.434783
max        1.000000
Name: horsepower, dtype: float64

In [ ]:
# 표준화 
# 평균은 0, 표준편차는 1이 되도록 변환 
# 이상치 파악
# (주어진 데이터값 - 평균값) / 표준편차

In [36]:
hp3 = (auto.horsepower - auto.horsepower.mean()) / auto.horsepower.std()
hp3.describe()

count    3.920000e+02
mean    -3.231542e-16
std      1.000000e+00
min     -1.519034e+00
25%     -7.656144e-01
50%     -2.849846e-01
75%      5.593651e-01
max      3.261284e+00
Name: horsepower, dtype: float64